about/urls.py
# -*- coding: utf-8 -*-
#from django.conf.urls import url, include
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.index, name='index'),
]

autorestore/urls.py
# -*- coding: utf-8 -*-
"""autorestore URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    # Added by -Grey-:
    path('', include('landing.urls')),
    path('about', include('about.urls')),
    path('news/', include('news.urls')),
    path('contacts', include('contacts.urls')),
    path('services', include('services.urls')),
]

contacts/urls.py
# -*- coding: utf-8 -*-
#from django.conf.urls import url, include
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.contacts, name='contacts'),
]

landing/urls.py
# -*- coding: utf-8 -*-
#from django.conf.urls import url, include
from . import views
from django.urls import path, include
from django.views.generic import ListView
from news.models import Article

urlpatterns = [
    path('', views.landing, name='landing'),
    path('', ListView.as_view(queryset=Article.objects.all().order_by("-date")[:2], template_name="landing/page.html")),
]

news/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from django.views.generic import ListView, DetailView
from news.models import Article

urlpatterns = [
    path('', ListView.as_view(queryset=Article.objects.all().order_by("-date")[:20], template_name="news/posts.html")),
    path('<int:pk>', DetailView.as_view(model=Article, template_name="news/post.html")),
]

services/urls.py
# -*- coding: utf-8 -*-
#from django.conf.urls import url, include
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.services, name='services'),
]

about/models.py
from django.db import models

# Create your models here.

contacts/models.py
from django.db import models

class Mail(models.Model):
    name = models.CharField(max_length=128)
    telephone = models.CharField(max_length=20)
    email = models.EmailField()
    message = models.TextField(max_length=2048)

    def __str__(self):
        return self.title

landing/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Subscriber(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=256)

news/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length = 100)
    post = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title

services/models.py
from django.db import models

# Create your models here.

contacts/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import *

class MailForm(forms.ModelForm):

    class Meta:
        model = Mail
        exclude = [""]

landing/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import *

class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        exclude = [""]

about/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

def index(request):
    return render(request, 'about/page.html', locals())

contacts/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .forms import MailForm


def contacts(request):
    name = "Grey"
    current_day = "27.01.2019"
    form = MailForm(request.POST or None)

    if request.method == "POST":
#        print(form)
        print(request.POST)

    return render(request, 'contacts/page.html', locals())

landing/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
# Добавлено:
from landing.forms import SubscriberForm

def landing(request):
    form = SubscriberForm(request.POST or None)

    if request.method == "POST" and form.is_valid(): # пока в душе не знаю, нах.. эти две строчки
#        print(request.POST)
        print(form.cleaned_data)
        data = form.cleaned_data
        print(data["name"])

        new_form = form.save()

    return render(request, 'landing/page.html', locals())

news/views.py
from django.shortcuts import render

# Create your views here.

services/views.py
from django.shortcuts import render


def services(request):
    return render(request, 'services/page.html', locals())

about/templates/about/includes/body.html
{% load staticfiles %}

<!-- Body -->
<section class="introtext about1">
    <div class="row">
        <div class="col-sm-12">
            <h2>О НАШЕЙ КОМПАНИИ</h2>
            <p>Специализированный Автотехцентр: Мы предлагаем весь комплекс работ для наилучшего состояния Вашего автомобиля. Обслуживание у нас означает высшее качество выполненных работ по ремонту и уходу за автомобилем. Для качественного ремонта современных автомобилей необходимы оборудование и целенаправленные специалисты. Поэтому, наш техцентр оснащен всеми необходимыми инструментами, спец инструментами и аппаратурой, у нас работают только опытные специалисты. Именно поэтому мы выполняем только качественный ремонт.</p>
            <p>Мы не боимся трудностей и беремся за самые сложные и, на первый взгляд, невыполнимые работы. Для нас нет неразрешимых задач.</p>
        </div>
    </div>
</section>
<div class="spacing-65">

</div>
<!-- End of Body -->

about/templates/about/includes/header.html
{% load staticfiles %}

<!-- HEADER -->

<div id="hw-hero">
    <div class="header header1">

        <!-- TOP BAR -->
        <div class="topbar">
            <div class="row">
                <div class="col-sm-6">
                    <ul class="phone">
                        <li><span class="typcn typcn-location-outline"></span> Санкт-Петербург, Киришская ул., д.4а</li>
                        <li><a href="tel:8 800 600 7218"><span class="typcn typcn-phone-outline"></span> 8 800 600 7218</a></li>
                    </ul>
                </div>
                <div class="col-sm-6">
                    <ul class="toplinks">
                        <li>ПН - ПТ 09:00 - 21:00</li>
                        <li><a href="mailto:info@paynspray.ru">info@paynspray.ru</a></li>
                        <!-- <li><a href="#search" title="Заказ обратного звонка"><i class="fa fa-phone"></i> Заказать звонок</a></li> -->
                    </ul>
                </div>
            </div>
        </div>
        <!-- END OF TOP BAR -->
        <!-- LOGO & NAVIGATION -->
        <div class="header-navigation">
            <div class="row">
                <div class="col-sm-12">
                    <div class="logonav">
                        <div class="row no-gutter">
                            <div class="col-sm-3">
                                <div class="logo">
                                    <a href="/"><img src="{% static "landing/image/logo.png" %}" /></a>
                                </div>
                            </div>
                            <div class="col-sm-9">
                                <nav id="desktop-menu">
                                    <ul class="sf-menu" id="navigation">
                                        <li><a href="/">Главная</a></li><li><a href="/about">О компании</a></li><li><a href="/services">Услуги</a></li><li><a href="/news">Новости и акции</a></li><li><a href="/contacts">Контакты</a></li></ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END OF LOGO & NAVIGATION -->
    </div>

    <!-- PAGE HEADER -->
    <div id="page-header" class="about1">
        <div class="title-breadcrumbs">
            <h1>О КОМПАНИИ</h1>
            <div class="thebreadcumb">
                <ul class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li class="active">О КОМПАНИИ</li>
                </ul>
            </div>
        </div>

    </div>
    <!-- END OF PAGE HEADER -->
</div>

about/templates/about/page.html
{% extends "landing/wrapper.html" %}

{% block content %}
    {% include "about/includes/header.html" %}
    {% include "about/includes/body.html" %}
    {% include "landing/includes/footer.html" %}
{% endblock %}

contacts/templates/contacts/includes/address.html
{% load staticfiles %}
<!-- ADDRESS -->
<div class="shell">
    <div class="box box-insets-off bg-white reveal-lg-block offset-top-30">
        <div class="range range-xs-center range-md-justify text-sm-left">
            <div class="cell-sm-8 cell-sm-push-1">
                <div class="box-inner">
                    <div class="range range-xs-center offset-top-10">
                        <div class="container">
                            <h4 class="text-ubold">Наши контакты</h4>
                            <br>
                            <div class="offset-top-25">
                                <address class="contact-info text-left">
                                    <p class="reveal-block text-small"><span
                                            class="unit unit-horizontal unit-spacing-xs">
                                        <span>Санкт-Петербург, Киришская ул., д.4а</span></span></span>
                                    </p>
                                    <div class="offset-top-20">
                                        <p class="reveal-inline-block text-small">
                                            <a href="tel:8 800 600 7218"><span class="typcn typcn-phone-outline"></span>
                                                8 800 600 7218</a>
                                        </p>
                                    </div>
                                    <div class="offset-top-20">
                                        <p class="reveal-inline-block text-small">
                                            <a href="mailto:info@paynspray.ru"><span class="typcn typcn-mail"></span>
                                                info@paynspray.ru</a>
                                        </p>
                                    </div>
                                    <div class="offset-top-20">
                                        <p><b>Владислав:</b></p>
                                        <p class="reveal-inline-block text-small">
                                            <a href="tel:+7 981 850-75-77"><span class="typcn typcn-phone-outline"></span>
                                                 +7 (981) 850-75-77</a>
                                        </p>
                                        <p class="reveal-inline-block text-small">
                                            <a href="mailto:vlad@paynspray.ru"><span class="typcn typcn-mail"></span>
                                                vlad@paynspray.ru</a>
                                        </p>
                                        <p><b>Александр:</b></p>
                                        <p class="reveal-inline-block text-small">
                                            <a href="tel:+7 911 839-58-27"><span class="typcn typcn-phone-outline"></span>
                                                 +7 (911) 839-58-27</a>
                                        </p>
                                        <p class="reveal-inline-block text-small">
                                            <a href="mailto:aleksandr@paynspray.ru"><span class="typcn typcn-mail"></span>
                                                aleksandr@paynspray.ru</a>
                                        </p>
                                    </div>
                                </address>
                            </div>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--  END OF ADDRESS -->

contacts/templates/contacts/includes/form.html
{% load staticfiles %}

<!-- FORM -->
<section class="contact-form" style="margin-top:20px">
    <div class="row">
        <div class="col-sm-12">
            <h2>ОТПРАВЬТЕ НАМ <span>СООБЩЕНИЕ</span></h2>
            <hr class="small"/>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div id="sendstatus"></div>
            <div id="contactform">
                <form action="" method="post">{% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6">
                            <p><label for="id_name" class="form-label">Ваше имя</label> {{ form.name }}</p>
                            <p><label for="id_telephone" class="form-label">Ваш телефон</label> {{ form.telephone }}</p>
                            <p><label for="id_email" class="form-label">Ваш email</label> {{ form.email }}</p>
                        </div>
                        <div class="col-sm-6">
                            <p><label for="id_message" class="form-label">Сообщение</label> {{ form.message }}</p>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <p><button class="btn medium btn-royalblue" style="margin-bottom:40px" type="submit" tabindex="5">Отправить сообщение</button></p></center>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- END OF FORM -->

contacts/templates/contacts/includes/header.html
{% load staticfiles %}

<!-- HEADER -->

<div id="hw-hero">
    <div class="header header1">

        <!-- TOP BAR -->
        <div class="topbar">
            <div class="row">
                <div class="col-sm-6">
                    <ul class="phone">
                        <li><span class="typcn typcn-location-outline"></span> Санкт-Петербург, Киришская ул., д.4а</li>
                        <li><a href="tel:8 800 600 7218"><span class="typcn typcn-phone-outline"></span> 8 800 600 7218</a></li>
                    </ul>
                </div>
                <div class="col-sm-6">
                    <ul class="toplinks">
                        <li>ПН - ПТ 09:00 - 21:00</li>
                        <li><a href="mailto:info@paynspray.ru">info@paynspray.ru</a></li>
                        <!-- <li><a href="#search" title="Заказ обратного звонка"><i class="fa fa-phone"></i> Заказать звонок</a></li> -->
                    </ul>
                </div>
            </div>
        </div>
        <!-- END OF TOP BAR -->
        <!-- LOGO & NAVIGATION -->
        <div class="header-navigation">
            <div class="row">
                <div class="col-sm-12">
                    <div class="logonav">
                        <div class="row no-gutter">
                            <div class="col-sm-3">
                                <div class="logo">
                                    <a href="/"><img src="{% static "landing/image/logo.png" %}" /></a>
                                </div>
                            </div>
                            <div class="col-sm-9">
                                <nav id="desktop-menu">
                                    <ul class="sf-menu" id="navigation">
                                        <li><a href="/">Главная</a></li><li><a href="/about">О компании</a></li><li><a href="/services">Услуги</a></li><li><a href="/news">Новости и акции</a></li><li><a href="/contacts">Контакты</a></li></ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END OF LOGO & NAVIGATION -->
    </div>

    <!-- PAGE HEADER -->
    <div id="page-header" class="about1">
        <div class="title-breadcrumbs">
            <h1>КОНТАКТЫ</h1>
            <div class="thebreadcumb">
                <ul class="breadcrumb">
                    <li><a href="/">Главная</a></li>
                    <li class="active">КОНТАКТЫ</li>
                </ul>
            </div>
        </div>

    </div>
    <!-- END OF PAGE HEADER -->
</div>

contacts/templates/contacts/includes/map.html
{% load staticfiles %}

<div style="height:550px">
    <iframe src="https://yandex.ru/map-widget/v1/-/CBRTq0E0oA" width="100%25" height="550" frameborder="1" allowfullscreen="true"></iframe>
</div>
<div class="spacing-65">

</div>

contacts/templates/contacts/page.html
{% extends "landing/wrapper.html" %}

{% block content %}
    {% include "contacts/includes/header.html" %}
    {% include "contacts/includes/address.html" %}
    {% include "contacts/includes/map.html" %}
    {% include "landing/includes/footer.html" %}
{% endblock %}

landing/templates/landing/includes/clients.html
<!-- CLIENTS -->
{% load staticfiles %}
<section class="clients home2 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="450ms">
    <div class="row">
        <div class="col-sm-12">
            <h2>МЫ РАБОТАЕМ СО ВСЕМИ МАРКАМИ АВТОМОБИЛЕЙ</h2>
            <p class="text-center">У нас есть для этого все необходимое! Высококлассные специалисты. Профессиональное
                оборудование. Автозапчасти.</p>
            <div id="clients-carousel" class="owl-carousel">

                <div class="item" title="Ауди"><img src="{% static "landing/image/clients/cli_0001.png" %}" alt=""/>
                </div>
                <div class="item" title="БМВ"><img src="{% static "landing/image/clients/cli_0002.png" %}" alt=""/>
                </div>
                <div class="item" title="Инфинити"><img src="{% static "landing/image/clients/cli_0003.png" %}" alt=""/>
                </div>
                <div class="item" title="Лексус"><img src="{% static "landing/image/clients/cli_0004.png" %}" alt=""/>
                </div>
                <div class="item" title="Land Rover"><img src="{% static "landing/image/clients/cli_0005.png" %}"
                                                          alt=""/>
                </div>
                <div class="item" title="Мини"><img src="{% static "landing/image/clients/cli_0006.png" %}" alt=""/>
                </div>
                <div class="item" title="Мерседес"><img src="{% static "landing/image/clients/cli_0007.png" %}" alt=""/>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END CLIENTS -->

landing/templates/landing/includes/features.html
<!-- Feauters -->
<section class="introtext home2">
    <div class="row spacing-20">
        <div class="col-sm-12">
        <div class="block-grid-sm-4 block-grid-xs-1">
            <div class="block-grid-item wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                <span class="typcn typcn-star"></span>
                <h3>БОЛЬШОЙ ОПЫТ</h3>
                <p>Более 5 лет – опыт обслуживания и ремонта автомобилей.</p>
            </div>
            <div class="block-grid-item wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                <span class="typcn typcn-group"></span>
                <h3>ПРОФЕССИОНАЛЫ</h3>
                <p>Высокая квалификация и профессионализм персонала.</p>
            </div>
            <div class="block-grid-item wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                <span class="typcn typcn-watch"></span>
                <h3>СОБЛЮДЕНИЕ СРОКОВ</h3>
                <p>Соблюдение сроков и стоимости работ.</p>
            </div>
            <div class="block-grid-item wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                <span class="typcn typcn-thumbs-up"></span>
                <h3>ГАРАНТИЯ КАЧЕСТВА</h3>
                <p>Гарантируем высокое качество работ.</p>
            </div>        
        </div>
        </div>
    </div>
</section>
<!-- End of Features -->

landing/templates/landing/includes/footer.html
<!-- Footer -->
<section class="footer">

    <div class="footer-elements">
        <div class="row">
            <div class="col-sm-12">
                <div class="row no-gutter">
                    <!-- Footer top element -->
                    <div class="col-sm-3">
                        <div class="footer-element">
                            <span class="typcn typcn-watch"></span>
                            <p>ВРЕМЯ РАБОТЫ:<span>ПН - ПТ 09:00 - 21:00</span></p>
                        </div>
                    </div>
                    <!-- Footer top element -->
                    <!-- Footer top element -->
                    <div class="col-sm-3">
                        <div class="footer-element">
                            <span class="typcn typcn-location-outline"></span>
                            <p>АДРЕС:<span>Санкт-Петербург, Киришская ул., д.4а</span></p>
                        </div>
                    </div>
                    <!-- Footer top element -->
                    <!-- Footer top element -->
                    <div class="col-sm-3">
                        <div class="footer-element">
                            <span class="typcn typcn-mail"></span>
                            <p>E-MAIL:<span><a href="mailto:info@paynspray.ru">info@paynspray.ru</a></span></p>
                        </div>
                    </div>
                    <!-- Footer top element -->
                    <!-- Footer top element -->
                    <div class="col-sm-3">
                        <div class="footer-element">
                            <span class="typcn typcn-phone-outline"></span>
                            <p>ТЕЛЕФОН:<span><a href="tel:8 800 600 7218">8 800 600 7218</a></span></p>
                        </div>
                    </div>
                    <!-- Footer top element -->
                </div>
            </div>
        </div>
    </div>
    <div class="footer-widgets">
        <div class="row">
            <!-- Footer widget -->
            <div class="col-sm-4">
                <div class="footer-widget">
                    <h5>О НАС</h5>
                    <p>Центр покраски и восстановления автомобиля Pay'n'Spray: Мы обеспечиваем широкий спектр услуг для наилучшего состояния вашего автомобиля. У нас вы можете успешно и быстро производить диагностику автомобиля и ремонт любой сложности. Наши специалисты высочайшей квалификации - гарантия качества выполненных работ</p>
                </div>
            </div>
            <!-- End of Footer widget -->
            <!-- Footer widget -->
            <div class="col-sm-4">
                <div class="footer-widget">
                    <h5>НОВОСТИ</h5>
                    <ul class="posts">
                        {% for post in object_list %}
                            <li>
                                <a href="/news/{{ post.id }}">{{ post.title }}</a>
                                <span>{{ post.date|date:"d-m-Y" }}</span>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <!-- End of Footer widget -->
            <!-- Footer widget -->
            <div class="col-sm-4">
                <div class="footer-widget">
                    <h5>МЕНЮ</h5>
                    <ul class="posts">
                        <li><a href="/">Главная</a></li>
                        <li><a href="/about">О компании</a></li>
                        <li><a href="/services">Услуги</a></li>
                        <li><a href="/news">Новости и акции</a></li>
                        <li><a href="/contacts">Контакты</a></li>
                    </ul>
                </div>
            </div>
            <!-- End of Footer widget -->
            <!-- Footer widget -->
            <!-- <div class="col-sm-3">
                <div class="footer-widget">
                        <h5>ЗАКАЗ ЗВОНКА</h5>
                        <p>Введите номер Вашего телефона</p>
                    <div id="back-box">
                        <form class="form-inline validate material" action="#" method="post" >
                        <input id="back-phone" type="text" placeholder="Телефон" required>
                        <input type="button" value="ЗАКАЗАТЬ ЗВОНОК" id="back-button" class="mtr-btn button-blue">
                        </form>
                    </div>
                    <div id="back-message" style="display:none; margin-top:40px;"><b style="color:#ffffff">Скоро мы Вам перезвоним!</b>
                    </div>
                </div>
            </div> -->
            <!-- End of Footer widget -->
        </div>
    </div>
</section>
<!-- End of Footer -->

landing/templates/landing/includes/gallery.html
{% load staticfiles %}
<!-- Gallery -->
<section class="projects">
    <div class="row">
        <div class="col-sm-12">
        <h2>ПРИМЕРЫ РАБОТ</h2>
        </div>
    </div>
    <div class="row full-width no-gutter-all">
        <div class="col-sm-12">
            <div class="block-grid-sm-4 block-grid-xs-1 projectsposts">
                <div class="block-grid-item wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                <a href="{% static "landing/image/gallery/st1_0001.jpg" %}" class="lightbox">
                    <figure>
                        <img src="{% static "landing/image/gallery/st1_0001.jpg" %}" />
                        <figcaption>
                            <div class="fig-overlay">
                                <div class="thetitle"><h6>Фото: Восстановление после ДТП</h6></div>
                            </div>
                        </figcaption>
                    </figure>
                </a>
                </div>
            <div class="block-grid-item wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
            <a href="{% static "landing/image/gallery/st1_0002.jpg" %}" class="lightbox">
                <figure>
                    <img src="{% static "landing/image/gallery/st1_0002.jpg" %}" />
                    <figcaption>
                        <div class="fig-overlay">
                            <div class="thetitle"><h6>Фото: Покраска после кузовных работ</h6></div>
                        </div>
                    </figcaption>
                </figure>
            </a>
            </div>
            <div class="block-grid-item wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
            <a href="{% static "landing/image/gallery/st1_0003.jpg" %}" class="lightbox">
                <figure>
                    <img src="{% static "landing/image/gallery/st1_0003.jpg" %}" />
                    <figcaption>
                        <div class="fig-overlay">
                            <div class="thetitle"><h6>Фото: Покраска кузова автомобиля</h6></div>
                        </div>
                    </figcaption>
                </figure>
            </a>
            </div>
                <div class="block-grid-item wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                <a href="{% static "landing/image/gallery/st1_0004.jpg" %}" class="lightbox">
                    <figure>
                        <img src="{% static "landing/image/gallery/st1_0004.jpg" %}" />
                        <figcaption>
                            <div class="fig-overlay">
                                <div class="thetitle"><h6>Фото: Тонировка стёкол</h6></div>
                            </div>
                        </figcaption>
                    </figure>
                    </a>
                </div>    
            </div>
        </div>
    </div>
</section>
<!-- End of Gallery -->

landing/templates/landing/includes/header.html
{% load staticfiles %}

<!-- HEADER -->

<div class="header header2">

    <!-- TOP BAR -->
    <div class="topbar">
        <div class="row">
            <div class="col-sm-6">
                <ul class="phone">
                    <li><span class="typcn typcn-location-outline"></span> Санкт-Петербург, Киришская ул., д.4а</li>
                    <li><a href="tel:8 800 600 7218"><span class="typcn typcn-phone-outline"></span> 8 800 600 7218</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-6">
                <ul class="toplinks">
                    <li>ПН - ПТ 09:00 - 21:00</li>
                    <li><a href="mailto:info@paynspray.ru">info@paynspray.ru</a></li>
                    <!-- <li><a href="#search" title="Заказ обратного звонка"><i class="fa fa-phone"></i> Заказать звонок</a></li> -->
                </ul>
            </div>
        </div>
    </div>
    <!-- END OF TOP BAR -->      <!-- SEARCH FORM -->
    <div id="search">
        <button type="button" class="close">x</button>
        <form id="form-back-call" onsubmit="return false">
            <span>Заказ обратного звонка. Введите номер Вашего телефона:</span>
            <input type="text" value="" placeholder=""/>
            <input type="button" value="ЗАКАЗАТЬ ЗВОНОК" id="form-back-button" class="mtr-btn button-blue"
                   style="margin-top:20px; border-radius:5px; width:100%; padding:15px; border:none; box-shadow:none; color:#fff; background:#28CB75;">
        </form>
        <div id="form-back-message" style="display:none; margin-top:220px;">
            <center><b style="font-size:24px">Заявка принята. Скоро мы Вам перезвоним!</b></center>
        </div>
    </div>
    <!-- END OF SEARCH FORM -->      <!-- LOGO & NAVIGATION -->
    <div class="header-navigation">
        <div class="row">
            <div class="col-sm-12">
                <div class="logonav">
                    <div class="row no-gutter">
                        <div class="col-sm-3">
                            <div class="logo">
                                <a href="/"><img src="{% static "landing/image/logo.png" %}"/></a>
                            </div>
                        </div>
                        <div class="col-sm-9">
                            <nav id="desktop-menu">
                                <ul class="sf-menu" id="navigation">
                                    <li><a href="/">Главная</a></li>
                                    <li><a href="/about">О компании</a></li>
                                    <li><a href="/services">Услуги</a></li>
                                    <li><a href="/news">Новости и акции</a></li>
                                    <li><a href="/contacts">Контакты</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END OF LOGO & NAVIGATION -->
</div>
<!-- END OF HEADER -->

landing/templates/landing/page.html
{% extends "landing/wrapper.html" %}

{% block content %}
    {% include "landing/includes/header.html" %}
    {% include "landing/includes/slider.html" %}
    {% include "landing/includes/features.html" %}
    {% include "landing/includes/gallery.html" %}
    {% include "landing/includes/testimonials.html" %}
    {% include "landing/includes/clients.html" %}
    {% include "landing/includes/footer.html" %}
{% endblock %}